# Maximum distance from 0,0 that players can spawn (in blocks)
spawn-radius: 300

# Maximum number of attempts to find a safe spawn location
max-spawn-attempts: 75

# Cooldown in seconds for using the /spawn command
spawn-cooldown: 5

# List of blocks that are considered unsafe to spawn on.
# This list is used as the default if the `unsafe-blocks` section in the config is empty.
unsafe-blocks:
  - LAVA
  - FIRE
  - CAMPFIRE
  - SOUL_CAMPFIRE
  - MAGMA_BLOCK
  - CACTUS
  - POWDER_SNOW
  - SWEET_BERRY_BUSH