# Maximum distance from 0,0 that players can spawn (in blocks)
spawn-radius: 300

# Maximum number of attempts to find a safe spawn location
max-spawn-attempts: 75

# Cooldown in seconds for using the /spawn command
spawn-cooldown: 5

# List of blocks that are considered unsafe to spawn on.
# This list is used as the default if the `unsafe-blocks` section in the config is empty.
unsafe-blocks:
  - LAVA
  - WATER
  - CACTUS
  - FIRE
  - MAGMA_BLOCK
  - SWEET_BERRY_BUSH
  - POWDER_SNOW
  - PALE_OAK_LEAVES
  - BIRCH_LEAVES
  - OAK_LEAVES
  - DARK_OAK_LEAVES
  - STONE
  - COPPER_ORE
  - WAXED_OXIDIZED_COPPER
  - SPRUCE_LEAVES
  - CLAY
  - OAK_PLANKS
  - DEEPSLATE
  - RED_MUSHROOM_BLOCK
  - GRAVEL
  - DIORITE
  - GRANITE
  - MOSS_BLOCK
  - OWN_MUSHROOM_BLOCK
  - TUFF
  - AMETHYST_BLOCK
  - CALCITE
  - SMOOTH_BASALT
  - SCULK
  - GRAY_WOOL
  - DEEPSLATE_BRICKS
  - POLISHED_DEEPSLATE
  - WAXED_COPPER_GRATE
  - MOSSY_COBBLESTONE
  - COBBLESTONE
  - SCULK_SENSOR
  - ANDESITE
  - DRIPSTONE_BLOCK
  - WAXED_COPPER_BLOCK
  - POINTED_DRIPSTONE
  - SCULK_VEIN
  - COAL_ORE
  - BROWN_MUSHROOM_BLOCK
  - DIRT
  - TUFF_BRICKS
  - DEEPSLATE_REDSTONE_ORE
  - CRACKED_DEEPSLATE_BRICKS
  - DARK_OAK_PLANKS
  - CHISELED_DEEPSLATE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_TILE_STAIRS
  - REDSTONE_ORE
  - DEEPSLATE_LAPIS_ORE
  - WAXED_OXIDIZED_CUT_COPPER
  - DEEPSLATE_TILES
  - NOTE_BLOCK
  - CRACKED_DEEPSLATE_TILES
